#!/bin/sh
# SOURCE: https://wiki.archlinux.org/title/Simple_stateful_firewall

# Load empty rules
iptables-restore </etc/iptables/empty.rules

# Create TCP and UDP chains
iptables -N TCP
iptables -N UDP

# Don't forward packets
iptables -P FORWARD DROP

# Allow outbound traffic
# TODO: restrict/harden
iptables -P OUTPUT ACCEPT

# Deny incoming traffic by default
iptables -P INPUT DROP

# Allow related/established traffic using conntrack module
iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

# Allow loopback traffic
# TODO: determine if necessary
iptables -A INPUT -i lo -j ACCEPT

# Deny invalid packets
iptables -A INPUT -m conntrack --ctstate INVALID -j DROP

# Allow ICMP pings
# TODO: determine if necessary
iptables -A INPUT -p icmp --icmp-type 8 -m conntrack --ctstate NEW -j ACCEPT

# Handle TCP/UDP connections
iptables -A INPUT -p udp -m conntrack --ctstate NEW -j UDP
iptables -A INPUT -p tcp --syn -m conntrack --ctstate NEW -j TCP

# Reject unreachable ICMP messages
iptables -A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable

# Reject TCP RESET packets
iptables -A INPUT -p tcp -j REJECT --reject-with tcp-reset

# Reject ICMP protocol unreachable messages
iptables -A INPUT -j REJECT --reject-with icmp-proto-unreachable

iptables-save -f /etc/iptables/iptables.rules
