#!/usr/bin/env bash
# SOURCE: https://wiki.archlinux.org/title/Simple_stateful_firewall

# Load empty rules
cat <<EOF | iptables-restore
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
EOF

# Create TCP and UDP chains
iptables -N TCP
iptables -N UDP

# Don't forward packets
iptables -P FORWARD DROP

# Allow outbound traffic
# TODO: restrict/harden
iptables -P OUTPUT ACCEPT

# Deny incoming traffic by default
iptables -P INPUT DROP

# Allow related/established traffic using conntrack module
iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

# Allow loopback traffic
# TODO: determine if necessary
iptables -A INPUT -i lo -j ACCEPT

# Deny invalid packets
iptables -A INPUT -m conntrack --ctstate INVALID -j DROP

# Allow ICMP pings
# TODO: determine if necessary
iptables -A INPUT -p icmp --icmp-type 8 -m conntrack --ctstate NEW -j ACCEPT

# Handle TCP/UDP connections
iptables -A INPUT -p udp -m conntrack --ctstate NEW -j UDP
iptables -A INPUT -p tcp --syn -m conntrack --ctstate NEW -j TCP

# Reject unreachable ICMP messages
iptables -A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable

# Reject TCP RESET packets
iptables -A INPUT -p tcp -j REJECT --reject-with tcp-reset

# Reject ICMP protocol unreachable messages
iptables -A INPUT -j REJECT --reject-with icmp-proto-unreachable

if ! [[ -d /etc/iptables ]]; then
  mkdir -p /etc/iptables/
fi
iptables-save -f /etc/iptables/iptables.rules

if ! systemctl status iptables.service &>/dev/null; then
  cat <<EOF >/etc/systemd/system/iptables.service
[Unit]
Description=IPv4 Packet Filtering Framework
Before=network-pre.target
Wants=network-pre.target

[Service]
Type=oneshot
ExecStart=/usr/bin/iptables-restore /etc/iptables/iptables.rules
ExecReload=/usr/bin/iptables-restore /etc/iptables/iptables.rules
ExecStop=/usr/lib/systemd/scripts/iptables-flush
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
fi

systemctl enable --now iptables.service
